
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>V2</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Items\Voraria\Weapons\Ranged\Throwables\ThrowableHoneyBottle.png" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BetterDialogue">
      <HintPath>..\BetterDialogue\bin\Debug\net6.0\BetterDialogue.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>