using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using V2.Core;
using V2.PlayerHandling;
using V2.PlayerHandling.PredPlayerGoals.Amateur;
using V2.PlayerHandling.PredPlayerGoals.Skilled;

namespace V2.Items.ItemGroupUtils
{
	public partial class Furniture
	{
		public static Dictionary<int, (FurnitureType Type, FurnitureMaterial Material)> FurnitureDefinitionMappings => new Dictionary<int, (FurnitureType, FurnitureMaterial)>
		{
			// Oak Wood furniture
			{ ItemID.Bed,                            (FurnitureType.Bed,          FurnitureMaterial.OakWood) },
			{ ItemID.Bookcase,                       (FurnitureType.Bookcase,     FurnitureMaterial.OakWood) },
			{ ItemID.WoodenChair,                    (FurnitureType.Chair,        FurnitureMaterial.OakWood) },
			{ ItemID.Chest,                          (FurnitureType.Chest,        FurnitureMaterial.OakWood) },
			{ ItemID.Fake_Chest,                     (FurnitureType.ChestTrapped, FurnitureMaterial.OakWood) },
			{ ItemID.GrandfatherClock,               (FurnitureType.Clock,        FurnitureMaterial.OakWood) },
			{ ItemID.WoodenDoor,                     (FurnitureType.Door,         FurnitureMaterial.OakWood) },
			{ ItemID.TallGate,                       (FurnitureType.DoorTall,     FurnitureMaterial.OakWood) },
			{ ItemID.Dresser,                        (FurnitureType.Dresser,      FurnitureMaterial.OakWood) },
			{ ItemID.WoodenFence,                    (FurnitureType.Fence,        FurnitureMaterial.OakWood) },
			{ ItemID.Piano,                          (FurnitureType.Piano,        FurnitureMaterial.OakWood) },
			{ ItemID.WoodPlatform,                   (FurnitureType.Platform,     FurnitureMaterial.OakWood) },
			{ ItemID.WoodenSink,                     (FurnitureType.Sink,         FurnitureMaterial.OakWood) },
			{ ItemID.Sofa,                           (FurnitureType.Sofa,         FurnitureMaterial.OakWood) },
			{ ItemID.WoodenTable,                    (FurnitureType.Table,        FurnitureMaterial.OakWood) },
			{ ItemID.WoodWall,                       (FurnitureType.Wall,         FurnitureMaterial.OakWood) },
			{ ItemID.WorkBench,                      (FurnitureType.WorkBench,    FurnitureMaterial.OakWood) },
			
			// Boreal Wood furniture
			{ ItemID.BorealWoodBathtub,              (FurnitureType.Bathtub,      FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodBed,                  (FurnitureType.Bed,          FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodBookcase,             (FurnitureType.Bookcase,     FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodCandelabra,           (FurnitureType.Candelabra,   FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodCandle,               (FurnitureType.Candle,       FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodChair,                (FurnitureType.Chair,        FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodChest,                (FurnitureType.Chest,        FurnitureMaterial.BorealWood) },
			{ ItemID.Fake_BorealWoodChest,           (FurnitureType.ChestTrapped, FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodClock,                (FurnitureType.Clock,        FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodDoor,                 (FurnitureType.Door,         FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodDresser,              (FurnitureType.Dresser,      FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodFence,                (FurnitureType.Fence,        FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodLamp,                 (FurnitureType.Lamp,         FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodLantern,              (FurnitureType.Lantern,      FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodPiano,                (FurnitureType.Piano,        FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodPlatform,             (FurnitureType.Platform,     FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodSink,                 (FurnitureType.Sink,         FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodSofa,                 (FurnitureType.Sofa,         FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodTable,                (FurnitureType.Table,        FurnitureMaterial.BorealWood) },
			{ ItemID.ToiletBoreal,                   (FurnitureType.Toilet,       FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodWall,                 (FurnitureType.Wall,         FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodWorkBench,            (FurnitureType.WorkBench,    FurnitureMaterial.BorealWood) },
			
			// Ebonwood furniture
			{ ItemID.EbonwoodBathtub,                (FurnitureType.Bathtub,      FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodBed,                    (FurnitureType.Bed,          FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodBookcase,               (FurnitureType.Bookcase,     FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodCandelabra,             (FurnitureType.Candelabra,   FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodCandle,                 (FurnitureType.Candle,       FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodChair,                  (FurnitureType.Chair,        FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodChest,                  (FurnitureType.Chest,        FurnitureMaterial.Ebonwood) },
			{ ItemID.Fake_EbonwoodChest,             (FurnitureType.ChestTrapped, FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodClock,                  (FurnitureType.Clock,        FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodDoor,                   (FurnitureType.Door,         FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodDresser,                (FurnitureType.Dresser,      FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodFence,                  (FurnitureType.Fence,        FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodLamp,                   (FurnitureType.Lamp,         FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodLantern,                (FurnitureType.Lantern,      FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodPiano,                  (FurnitureType.Piano,        FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodPlatform,               (FurnitureType.Platform,     FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodSink,                   (FurnitureType.Sink,         FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodSofa,                   (FurnitureType.Sofa,         FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodTable,                  (FurnitureType.Table,        FurnitureMaterial.Ebonwood) },
			{ ItemID.ToiletEbonyWood,                (FurnitureType.Toilet,       FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodWall,                   (FurnitureType.Wall,         FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodWorkBench,              (FurnitureType.WorkBench,    FurnitureMaterial.Ebonwood) },
			
			// Shadewood furniture
			{ ItemID.ShadewoodBathtub,               (FurnitureType.Bathtub,      FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodBed,                   (FurnitureType.Bed,          FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodBookcase,              (FurnitureType.Bookcase,     FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodCandelabra,            (FurnitureType.Candelabra,   FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodCandle,                (FurnitureType.Candle,       FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodChair,                 (FurnitureType.Chair,        FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodChest,                 (FurnitureType.Chest,        FurnitureMaterial.Shadewood) },
			{ ItemID.Fake_ShadewoodChest,            (FurnitureType.ChestTrapped, FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodClock,                 (FurnitureType.Clock,        FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodDoor,                  (FurnitureType.Door,         FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodDresser,               (FurnitureType.Dresser,      FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodFence,                 (FurnitureType.Fence,        FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodLamp,                  (FurnitureType.Lamp,         FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodLantern,               (FurnitureType.Lantern,      FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodPiano,                 (FurnitureType.Piano,        FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodPlatform,              (FurnitureType.Platform,     FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodSink,                  (FurnitureType.Sink,         FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodSofa,                  (FurnitureType.Sofa,         FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodTable,                 (FurnitureType.Table,        FurnitureMaterial.Shadewood) },
			{ ItemID.ToiletShadewood,                (FurnitureType.Toilet,       FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodWall,                  (FurnitureType.Wall,         FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodWorkBench,             (FurnitureType.WorkBench,    FurnitureMaterial.Shadewood) },
			
			// Palm Wood furniture
			{ ItemID.PalmWoodBathtub,                (FurnitureType.Bathtub,      FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodBed,                    (FurnitureType.Bed,          FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodBookcase,               (FurnitureType.Bookcase,     FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodCandelabra,             (FurnitureType.Candelabra,   FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodCandle,                 (FurnitureType.Candle,       FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodChair,                  (FurnitureType.Chair,        FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodChest,                  (FurnitureType.Chest,        FurnitureMaterial.PalmWood) },
			{ ItemID.Fake_PalmWoodChest,             (FurnitureType.ChestTrapped, FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodClock,                  (FurnitureType.Clock,        FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodDoor,                   (FurnitureType.Door,         FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodDresser,                (FurnitureType.Dresser,      FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodFence,                  (FurnitureType.Fence,        FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodLamp,                   (FurnitureType.Lamp,         FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodLantern,                (FurnitureType.Lantern,      FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodPiano,                  (FurnitureType.Piano,        FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodPlatform,               (FurnitureType.Platform,     FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodSink,                   (FurnitureType.Sink,         FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodSofa,                   (FurnitureType.Sofa,         FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodTable,                  (FurnitureType.Table,        FurnitureMaterial.PalmWood) },
			{ ItemID.ToiletPalm,                     (FurnitureType.Toilet,       FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodWall,                   (FurnitureType.Wall,         FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodWorkBench,              (FurnitureType.WorkBench,    FurnitureMaterial.PalmWood) },
			
			// Rich Mahogany furniture
			{ ItemID.RichMahoganyBathtub,            (FurnitureType.Bathtub,      FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyBed,                (FurnitureType.Bed,          FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyBookcase,           (FurnitureType.Bookcase,     FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyCandelabra,         (FurnitureType.Candelabra,   FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyCandle,             (FurnitureType.Candle,       FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyChair,              (FurnitureType.Chair,        FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyChest,              (FurnitureType.Chest,        FurnitureMaterial.JungleWood) },
			{ ItemID.Fake_RichMahoganyChest,         (FurnitureType.ChestTrapped, FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyClock,              (FurnitureType.Clock,        FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyDoor,               (FurnitureType.Door,         FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyDresser,            (FurnitureType.Dresser,      FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyFence,              (FurnitureType.Fence,        FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyLamp,               (FurnitureType.Lamp,         FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyLantern,            (FurnitureType.Lantern,      FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyPiano,              (FurnitureType.Piano,        FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyPlatform,           (FurnitureType.Platform,     FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganySink,               (FurnitureType.Sink,         FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganySofa,               (FurnitureType.Sofa,         FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyTable,              (FurnitureType.Table,        FurnitureMaterial.JungleWood) },
			{ ItemID.ToiletRichMahogany,             (FurnitureType.Toilet,       FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyWall,               (FurnitureType.Wall,         FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyWorkBench,          (FurnitureType.WorkBench,    FurnitureMaterial.JungleWood) },
			
			// Pearlwood furniture
			{ ItemID.PearlwoodBathtub,               (FurnitureType.Bathtub,      FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodBed,                   (FurnitureType.Bed,          FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodBookcase,              (FurnitureType.Bookcase,     FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodCandelabra,            (FurnitureType.Candelabra,   FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodCandle,                (FurnitureType.Candle,       FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodChair,                 (FurnitureType.Chair,        FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodChest,                 (FurnitureType.Chest,        FurnitureMaterial.Pearlwood) },
			{ ItemID.Fake_PearlwoodChest,            (FurnitureType.ChestTrapped, FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodClock,                 (FurnitureType.Clock,        FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodDoor,                  (FurnitureType.Door,         FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodDresser,               (FurnitureType.Dresser,      FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodFence,                 (FurnitureType.Fence,        FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodLamp,                  (FurnitureType.Lamp,         FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodLantern,               (FurnitureType.Lantern,      FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodPiano,                 (FurnitureType.Piano,        FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodPlatform,              (FurnitureType.Platform,     FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodSink,                  (FurnitureType.Sink,         FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodSofa,                  (FurnitureType.Sofa,         FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodTable,                 (FurnitureType.Table,        FurnitureMaterial.Pearlwood) },
			{ ItemID.ToiletPearlwood,                (FurnitureType.Toilet,       FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodWall,                  (FurnitureType.Wall,         FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodWorkBench,             (FurnitureType.WorkBench,    FurnitureMaterial.Pearlwood) },
			
			// Ash Wood furniture
			{ ItemID.AshWoodBathtub,                 (FurnitureType.Bathtub,      FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodBed,                     (FurnitureType.Bed,          FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodBookcase,                (FurnitureType.Bookcase,     FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodCandelabra,              (FurnitureType.Candelabra,   FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodCandle,                  (FurnitureType.Candle,       FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodChair,                   (FurnitureType.Chair,        FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodChest,                   (FurnitureType.Chest,        FurnitureMaterial.AshWood) },
			{ ItemID.Fake_AshWoodChest,              (FurnitureType.ChestTrapped, FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodClock,                   (FurnitureType.Clock,        FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodDoor,                    (FurnitureType.Door,         FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodDresser,                 (FurnitureType.Dresser,      FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodFence,                   (FurnitureType.Fence,        FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodLamp,                    (FurnitureType.Lamp,         FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodLantern,                 (FurnitureType.Lantern,      FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodPiano,                   (FurnitureType.Piano,        FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodPlatform,                (FurnitureType.Platform,     FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodSink,                    (FurnitureType.Sink,         FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodSofa,                    (FurnitureType.Sofa,         FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodTable,                   (FurnitureType.Table,        FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodToilet,                  (FurnitureType.Toilet,       FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodWall,                    (FurnitureType.Wall,         FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodWorkbench,               (FurnitureType.WorkBench,    FurnitureMaterial.AshWood) },
			
			// Spooky Wood furniture
			{ ItemID.SpookyBathtub,                  (FurnitureType.Bathtub,      FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyBed,                      (FurnitureType.Bed,          FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyBookcase,                 (FurnitureType.Bookcase,     FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyCandelabra,               (FurnitureType.Candelabra,   FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyCandle,                   (FurnitureType.Candle,       FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyChair,                    (FurnitureType.Chair,        FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyChest,                    (FurnitureType.Chest,        FurnitureMaterial.SpookyWood) },
			{ ItemID.Fake_SpookyChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyClock,                    (FurnitureType.Clock,        FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyDoor,                     (FurnitureType.Door,         FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyDresser,                  (FurnitureType.Dresser,      FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyLamp,                     (FurnitureType.Lamp,         FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyLantern,                  (FurnitureType.Lantern,      FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyPiano,                    (FurnitureType.Piano,        FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyPlatform,                 (FurnitureType.Platform,     FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookySink,                     (FurnitureType.Sink,         FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookySofa,                     (FurnitureType.Sofa,         FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyTable,                    (FurnitureType.Table,        FurnitureMaterial.SpookyWood) },
			{ ItemID.ToiletSpooky,                   (FurnitureType.Toilet,       FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyWoodWall,                 (FurnitureType.Wall,         FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyWorkBench,                (FurnitureType.WorkBench,    FurnitureMaterial.SpookyWood) },
			
			// Bamboo furniture
			{ ItemID.BambooBathtub,                  (FurnitureType.Bathtub,      FurnitureMaterial.Bamboo) },
			{ ItemID.BambooBed,                      (FurnitureType.Bed,          FurnitureMaterial.Bamboo) },
			{ ItemID.BambooBookcase,                 (FurnitureType.Bookcase,     FurnitureMaterial.Bamboo) },
			{ ItemID.BambooCandelabra,               (FurnitureType.Candelabra,   FurnitureMaterial.Bamboo) },
			{ ItemID.BambooCandle,                   (FurnitureType.Candle,       FurnitureMaterial.Bamboo) },
			{ ItemID.BambooChair,                    (FurnitureType.Chair,        FurnitureMaterial.Bamboo) },
			{ ItemID.BambooChest,                    (FurnitureType.Chest,        FurnitureMaterial.Bamboo) },
			{ ItemID.Fake_BambooChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.Bamboo) },
			{ ItemID.BambooClock,                    (FurnitureType.Clock,        FurnitureMaterial.Bamboo) },
			{ ItemID.BambooDoor,                     (FurnitureType.Door,         FurnitureMaterial.Bamboo) },
			{ ItemID.BambooDresser,                  (FurnitureType.Dresser,      FurnitureMaterial.Bamboo) },
			{ ItemID.BambooFence,                    (FurnitureType.Fence,        FurnitureMaterial.Bamboo) },
			{ ItemID.BambooLamp,                     (FurnitureType.Lamp,         FurnitureMaterial.Bamboo) },
			{ ItemID.BambooLantern,                  (FurnitureType.Lantern,      FurnitureMaterial.Bamboo) },
			{ ItemID.BambooPiano,                    (FurnitureType.Piano,        FurnitureMaterial.Bamboo) },
			{ ItemID.BambooPlatform,                 (FurnitureType.Platform,     FurnitureMaterial.Bamboo) },
			{ ItemID.BambooSink,                     (FurnitureType.Sink,         FurnitureMaterial.Bamboo) },
			{ ItemID.BambooSofa,                     (FurnitureType.Sofa,         FurnitureMaterial.Bamboo) },
			{ ItemID.BambooTable,                    (FurnitureType.Table,        FurnitureMaterial.Bamboo) },
			{ ItemID.BambooToilet,                   (FurnitureType.Toilet,       FurnitureMaterial.Bamboo) },
			{ ItemID.BambooBlockWall,                (FurnitureType.Wall,         FurnitureMaterial.Bamboo) },
			{ ItemID.BambooWorkbench,                (FurnitureType.WorkBench,    FurnitureMaterial.Bamboo) },
			
			// Cactus furniture
			{ ItemID.CactusBathtub,                  (FurnitureType.Bathtub,      FurnitureMaterial.Cactus) },
			{ ItemID.CactusBed,                      (FurnitureType.Bed,          FurnitureMaterial.Cactus) },
			{ ItemID.CactusBookcase,                 (FurnitureType.Bookcase,     FurnitureMaterial.Cactus) },
			{ ItemID.CactusCandelabra,               (FurnitureType.Candelabra,   FurnitureMaterial.Cactus) },
			{ ItemID.CactusCandle,                   (FurnitureType.Candle,       FurnitureMaterial.Cactus) },
			{ ItemID.CactusChair,                    (FurnitureType.Chair,        FurnitureMaterial.Cactus) },
			{ ItemID.CactusChest,                    (FurnitureType.Chest,        FurnitureMaterial.Cactus) },
			{ ItemID.Fake_CactusChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.Cactus) },
			{ ItemID.CactusClock,                    (FurnitureType.Clock,        FurnitureMaterial.Cactus) },
			{ ItemID.CactusDoor,                     (FurnitureType.Door,         FurnitureMaterial.Cactus) },
			{ ItemID.CactusDresser,                  (FurnitureType.Dresser,      FurnitureMaterial.Cactus) },
			{ ItemID.CactusLamp,                     (FurnitureType.Lamp,         FurnitureMaterial.Cactus) },
			{ ItemID.CactusLantern,                  (FurnitureType.Lantern,      FurnitureMaterial.Cactus) },
			{ ItemID.CactusPiano,                    (FurnitureType.Piano,        FurnitureMaterial.Cactus) },
			{ ItemID.CactusPlatform,                 (FurnitureType.Platform,     FurnitureMaterial.Cactus) },
			{ ItemID.CactusSink,                     (FurnitureType.Sink,         FurnitureMaterial.Cactus) },
			{ ItemID.CactusSofa,                     (FurnitureType.Sofa,         FurnitureMaterial.Cactus) },
			{ ItemID.CactusTable,                    (FurnitureType.Table,        FurnitureMaterial.Cactus) },
			{ ItemID.ToiletCactus,                   (FurnitureType.Toilet,       FurnitureMaterial.Cactus) },
			{ ItemID.CactusWall,                     (FurnitureType.Wall,         FurnitureMaterial.Cactus) },
			{ ItemID.CactusWorkBench,                (FurnitureType.WorkBench,    FurnitureMaterial.Cactus) },
			
			// Pumpkin furniture
			{ ItemID.PumpkinBathtub,                 (FurnitureType.Bathtub,      FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinBed,                     (FurnitureType.Bed,          FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinBookcase,                (FurnitureType.Bookcase,     FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinCandelabra,              (FurnitureType.Candelabra,   FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinCandle,                  (FurnitureType.Candle,       FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinChair,                   (FurnitureType.Chair,        FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinChest,                   (FurnitureType.Chest,        FurnitureMaterial.Pumpkin) },
			{ ItemID.Fake_PumpkinChest,              (FurnitureType.ChestTrapped, FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinClock,                   (FurnitureType.Clock,        FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinDoor,                    (FurnitureType.Door,         FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinDresser,                 (FurnitureType.Dresser,      FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinLamp,                    (FurnitureType.Lamp,         FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinLantern,                 (FurnitureType.Lantern,      FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinPiano,                   (FurnitureType.Piano,        FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinPlatform,                (FurnitureType.Platform,     FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinSink,                    (FurnitureType.Sink,         FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinSofa,                    (FurnitureType.Sofa,         FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinTable,                   (FurnitureType.Table,        FurnitureMaterial.Pumpkin) },
			{ ItemID.ToiletPumpkin,                  (FurnitureType.Toilet,       FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinWall,                    (FurnitureType.Wall,         FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinWorkBench,               (FurnitureType.WorkBench,    FurnitureMaterial.Pumpkin) },
			
			// Mushroom furniture
			{ ItemID.MushroomBathtub,                (FurnitureType.Bathtub,      FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomBed,                    (FurnitureType.Bed,          FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomBookcase,               (FurnitureType.Bookcase,     FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomCandelabra,             (FurnitureType.Candelabra,   FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomCandle,                 (FurnitureType.Candle,       FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomChair,                  (FurnitureType.Chair,        FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomChest,                  (FurnitureType.Chest,        FurnitureMaterial.Mushroom) },
			{ ItemID.Fake_MushroomChest,             (FurnitureType.ChestTrapped, FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomClock,                  (FurnitureType.Clock,        FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomDoor,                   (FurnitureType.Door,         FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomDresser,                (FurnitureType.Dresser,      FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomLamp,                   (FurnitureType.Lamp,         FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomLantern,                (FurnitureType.Lantern,      FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomPiano,                  (FurnitureType.Piano,        FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomPlatform,               (FurnitureType.Platform,     FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomSink,                   (FurnitureType.Sink,         FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomSofa,                   (FurnitureType.Sofa,         FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomTable,                  (FurnitureType.Table,        FurnitureMaterial.Mushroom) },
			{ ItemID.ToiletMushroom,                 (FurnitureType.Toilet,       FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomWall,                   (FurnitureType.Wall,         FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomWorkBench,              (FurnitureType.WorkBench,    FurnitureMaterial.Mushroom) },
			
			// Marble furniture
			{ ItemID.MarbleBathtub,                  (FurnitureType.Bathtub,      FurnitureMaterial.Marble) },
			{ ItemID.MarbleBed,                      (FurnitureType.Bed,          FurnitureMaterial.Marble) },
			{ ItemID.MarbleBookcase,                 (FurnitureType.Bookcase,     FurnitureMaterial.Marble) },
			{ ItemID.MarbleCandelabra,               (FurnitureType.Candelabra,   FurnitureMaterial.Marble) },
			{ ItemID.MarbleCandle,                   (FurnitureType.Candle,       FurnitureMaterial.Marble) },
			{ ItemID.MarbleChair,                    (FurnitureType.Chair,        FurnitureMaterial.Marble) },
			{ ItemID.MarbleChest,                    (FurnitureType.Chest,        FurnitureMaterial.Marble) },
			{ ItemID.Fake_MarbleChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.Marble) },
			{ ItemID.MarbleClock,                    (FurnitureType.Clock,        FurnitureMaterial.Marble) },
			{ ItemID.MarbleDoor,                     (FurnitureType.Door,         FurnitureMaterial.Marble) },
			{ ItemID.MarbleDresser,                  (FurnitureType.Dresser,      FurnitureMaterial.Marble) },
			{ ItemID.MarbleLamp,                     (FurnitureType.Lamp,         FurnitureMaterial.Marble) },
			{ ItemID.MarbleLantern,                  (FurnitureType.Lantern,      FurnitureMaterial.Marble) },
			{ ItemID.MarblePiano,                    (FurnitureType.Piano,        FurnitureMaterial.Marble) },
			{ ItemID.MarblePlatform,                 (FurnitureType.Platform,     FurnitureMaterial.Marble) },
			{ ItemID.MarbleSink,                     (FurnitureType.Sink,         FurnitureMaterial.Marble) },
			{ ItemID.MarbleSofa,                     (FurnitureType.Sofa,         FurnitureMaterial.Marble) },
			{ ItemID.MarbleTable,                    (FurnitureType.Table,        FurnitureMaterial.Marble) },
			{ ItemID.ToiletMarble,                   (FurnitureType.Toilet,       FurnitureMaterial.Marble) },
			{ ItemID.MarbleWall,                     (FurnitureType.Wall,         FurnitureMaterial.Marble) },
			{ ItemID.MarbleWorkBench,                (FurnitureType.WorkBench,    FurnitureMaterial.Marble) },
			
			// Granite furniture
			{ ItemID.GraniteBathtub,                 (FurnitureType.Bathtub,      FurnitureMaterial.Granite) },
			{ ItemID.GraniteBed,                     (FurnitureType.Bed,          FurnitureMaterial.Granite) },
			{ ItemID.GraniteBookcase,                (FurnitureType.Bookcase,     FurnitureMaterial.Granite) },
			{ ItemID.GraniteCandelabra,              (FurnitureType.Candelabra,   FurnitureMaterial.Granite) },
			{ ItemID.GraniteCandle,                  (FurnitureType.Candle,       FurnitureMaterial.Granite) },
			{ ItemID.GraniteChair,                   (FurnitureType.Chair,        FurnitureMaterial.Granite) },
			{ ItemID.GraniteChest,                   (FurnitureType.Chest,        FurnitureMaterial.Granite) },
			{ ItemID.Fake_GraniteChest,              (FurnitureType.ChestTrapped, FurnitureMaterial.Granite) },
			{ ItemID.GraniteClock,                   (FurnitureType.Clock,        FurnitureMaterial.Granite) },
			{ ItemID.GraniteDoor,                    (FurnitureType.Door,         FurnitureMaterial.Granite) },
			{ ItemID.GraniteDresser,                 (FurnitureType.Dresser,      FurnitureMaterial.Granite) },
			{ ItemID.GraniteLamp,                    (FurnitureType.Lamp,         FurnitureMaterial.Granite) },
			{ ItemID.GraniteLantern,                 (FurnitureType.Lantern,      FurnitureMaterial.Granite) },
			{ ItemID.GranitePiano,                   (FurnitureType.Piano,        FurnitureMaterial.Granite) },
			{ ItemID.GranitePlatform,                (FurnitureType.Platform,     FurnitureMaterial.Granite) },
			{ ItemID.GraniteSink,                    (FurnitureType.Sink,         FurnitureMaterial.Granite) },
			{ ItemID.GraniteSofa,                    (FurnitureType.Sofa,         FurnitureMaterial.Granite) },
			{ ItemID.GraniteTable,                   (FurnitureType.Table,        FurnitureMaterial.Granite) },
			{ ItemID.ToiletGranite,                  (FurnitureType.Toilet,       FurnitureMaterial.Granite) },
			{ ItemID.GraniteWall,                    (FurnitureType.Wall,         FurnitureMaterial.Granite) },
			{ ItemID.GraniteWorkBench,               (FurnitureType.WorkBench,    FurnitureMaterial.Granite) },
			
			// Sandstone furniture
			{ ItemID.SandstoneBathtub,               (FurnitureType.Bathtub,      FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneBed,                   (FurnitureType.Bed,          FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneBookcase,              (FurnitureType.Bookcase,     FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneCandelabra,            (FurnitureType.Candelabra,   FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneCandle,                (FurnitureType.Candle,       FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneChair,                 (FurnitureType.Chair,        FurnitureMaterial.Sandstone) },
			{ ItemID.DesertChest,                    (FurnitureType.Chest,        FurnitureMaterial.Sandstone) },
			{ ItemID.Fake_DesertChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneClock,                 (FurnitureType.Clock,        FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneDoor,                  (FurnitureType.Door,         FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneDresser,               (FurnitureType.Dresser,      FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneLamp,                  (FurnitureType.Lamp,         FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneLantern,               (FurnitureType.Lantern,      FurnitureMaterial.Sandstone) },
			{ ItemID.SandstonePiano,                 (FurnitureType.Piano,        FurnitureMaterial.Sandstone) },
			{ ItemID.SandstonePlatform,              (FurnitureType.Platform,     FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneSink,                  (FurnitureType.Sink,         FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneSofa,                  (FurnitureType.Sofa,         FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneTable,                 (FurnitureType.Table,        FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneToilet,                (FurnitureType.Toilet,       FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneWall,                  (FurnitureType.Wall,         FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneWorkbench,             (FurnitureType.WorkBench,    FurnitureMaterial.Sandstone) },
			
			// Frozen furniture
			{ ItemID.FrozenBathtub,                  (FurnitureType.Bathtub,      FurnitureMaterial.Ice) },
			{ ItemID.FrozenBed,                      (FurnitureType.Bed,          FurnitureMaterial.Ice) },
			{ ItemID.FrozenBookcase,                 (FurnitureType.Bookcase,     FurnitureMaterial.Ice) },
			{ ItemID.FrozenCandelabra,               (FurnitureType.Candelabra,   FurnitureMaterial.Ice) },
			{ ItemID.FrozenCandle,                   (FurnitureType.Candle,       FurnitureMaterial.Ice) },
			{ ItemID.FrozenChair,                    (FurnitureType.Chair,        FurnitureMaterial.Ice) },
			{ ItemID.FrozenChest,                    (FurnitureType.Chest,        FurnitureMaterial.Ice) },
			{ ItemID.Fake_FrozenChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.Ice) },
			{ ItemID.FrozenClock,                    (FurnitureType.Clock,        FurnitureMaterial.Ice) },
			{ ItemID.FrozenDoor,                     (FurnitureType.Door,         FurnitureMaterial.Ice) },
			{ ItemID.FrozenDresser,                  (FurnitureType.Dresser,      FurnitureMaterial.Ice) },
			{ ItemID.FrozenLamp,                     (FurnitureType.Lamp,         FurnitureMaterial.Ice) },
			{ ItemID.FrozenLantern,                  (FurnitureType.Lantern,      FurnitureMaterial.Ice) },
			{ ItemID.FrozenPiano,                    (FurnitureType.Piano,        FurnitureMaterial.Ice) },
			{ ItemID.FrozenPlatform,                 (FurnitureType.Platform,     FurnitureMaterial.Ice) },
			{ ItemID.FrozenSink,                     (FurnitureType.Sink,         FurnitureMaterial.Ice) },
			{ ItemID.FrozenSofa,                     (FurnitureType.Sofa,         FurnitureMaterial.Ice) },
			{ ItemID.FrozenTable,                    (FurnitureType.Table,        FurnitureMaterial.Ice) },
			{ ItemID.ToiletFrozen,                   (FurnitureType.Toilet,       FurnitureMaterial.Ice) },
			{ ItemID.FrozenWorkBench,                (FurnitureType.WorkBench,    FurnitureMaterial.Ice) },
			
			// Reef furniture
			{ ItemID.CoralBathtub,                   (FurnitureType.Bathtub,      FurnitureMaterial.Coral) },
			{ ItemID.CoralBed,                       (FurnitureType.Bed,          FurnitureMaterial.Coral) },
			{ ItemID.CoralBookcase,                  (FurnitureType.Bookcase,     FurnitureMaterial.Coral) },
			{ ItemID.CoralCandelabra,                (FurnitureType.Candelabra,   FurnitureMaterial.Coral) },
			{ ItemID.CoralCandle,                    (FurnitureType.Candle,       FurnitureMaterial.Coral) },
			{ ItemID.CoralChair,                     (FurnitureType.Chair,        FurnitureMaterial.Coral) },
			{ ItemID.CoralChest,                     (FurnitureType.Chest,        FurnitureMaterial.Coral) },
			{ ItemID.Fake_CoralChest,                (FurnitureType.ChestTrapped, FurnitureMaterial.Coral) },
			{ ItemID.CoralClock,                     (FurnitureType.Clock,        FurnitureMaterial.Coral) },
			{ ItemID.CoralDoor,                      (FurnitureType.Door,         FurnitureMaterial.Coral) },
			{ ItemID.CoralDresser,                   (FurnitureType.Dresser,      FurnitureMaterial.Coral) },
			{ ItemID.CoralLamp,                      (FurnitureType.Lamp,         FurnitureMaterial.Coral) },
			{ ItemID.CoralLantern,                   (FurnitureType.Lantern,      FurnitureMaterial.Coral) },
			{ ItemID.CoralPiano,                     (FurnitureType.Piano,        FurnitureMaterial.Coral) },
			{ ItemID.CoralPlatform,                  (FurnitureType.Platform,     FurnitureMaterial.Coral) },
			{ ItemID.CoralSink,                      (FurnitureType.Sink,         FurnitureMaterial.Coral) },
			{ ItemID.CoralSofa,                      (FurnitureType.Sofa,         FurnitureMaterial.Coral) },
			{ ItemID.CoralTable,                     (FurnitureType.Table,        FurnitureMaterial.Coral) },
			{ ItemID.CoralToilet,                    (FurnitureType.Toilet,       FurnitureMaterial.Coral) },
			{ ItemID.ReefWall,                       (FurnitureType.Wall,         FurnitureMaterial.Coral) },
			{ ItemID.CoralWorkbench,                 (FurnitureType.WorkBench,    FurnitureMaterial.Coral) },

			// Golden furniture (delicious shiny furniture....... :9)
			{ ItemID.GoldenBathtub,                  (FurnitureType.Bathtub,      FurnitureMaterial.Golden) },
			{ ItemID.GoldenBed,                      (FurnitureType.Bed,          FurnitureMaterial.Golden) },
			{ ItemID.GoldenBookcase,                 (FurnitureType.Bookcase,     FurnitureMaterial.Golden) },
			{ ItemID.GoldenCandelabra,               (FurnitureType.Candelabra,   FurnitureMaterial.Golden) },
			{ ItemID.GoldenCandle,                   (FurnitureType.Candle,       FurnitureMaterial.Golden) },
			{ ItemID.GoldenChair,                    (FurnitureType.Chair,        FurnitureMaterial.Golden) },
			{ ItemID.GoldenChandelier,               (FurnitureType.Chandelier,   FurnitureMaterial.Golden) },
			{ ItemID.GoldenChest,                    (FurnitureType.Chest,        FurnitureMaterial.Golden) },
			{ ItemID.Fake_GoldenChest,               (FurnitureType.ChestTrapped, FurnitureMaterial.Golden) },
			{ ItemID.GoldenClock,                    (FurnitureType.Clock,        FurnitureMaterial.Golden) },
			{ ItemID.GoldenDoor,                     (FurnitureType.Door,         FurnitureMaterial.Golden) },
			{ ItemID.GoldenDresser,                  (FurnitureType.Dresser,      FurnitureMaterial.Golden) },
			{ ItemID.GoldenLamp,                     (FurnitureType.Lamp,         FurnitureMaterial.Golden) },
			{ ItemID.GoldenLantern,                  (FurnitureType.Lantern,      FurnitureMaterial.Golden) },
			{ ItemID.GoldenPiano,                    (FurnitureType.Piano,        FurnitureMaterial.Golden) },
			{ ItemID.GoldenPlatform,                 (FurnitureType.Platform,     FurnitureMaterial.Golden) },
			{ ItemID.GoldenSink,                     (FurnitureType.Sink,         FurnitureMaterial.Golden) },
			{ ItemID.GoldenSofa,                     (FurnitureType.Sofa,         FurnitureMaterial.Golden) },
			{ ItemID.GoldenTable,                    (FurnitureType.Table,        FurnitureMaterial.Golden) },
			{ ItemID.GoldenToilet,                   (FurnitureType.Toilet,       FurnitureMaterial.Golden) },
			{ ItemID.GoldenWorkbench,                (FurnitureType.WorkBench,    FurnitureMaterial.Golden) },

			// Crystal furniture (how does that even work?)
			{ ItemID.CrystalBathtub,                 (FurnitureType.Bathtub,      FurnitureMaterial.Crystal) },
			{ ItemID.CrystalBed,                     (FurnitureType.Bed,          FurnitureMaterial.Crystal) },
			{ ItemID.CrystalBookCase,                (FurnitureType.Bookcase,     FurnitureMaterial.Crystal) },
			{ ItemID.CrystalCandelabra,              (FurnitureType.Candelabra,   FurnitureMaterial.Crystal) },
			{ ItemID.CrystalCandle,                  (FurnitureType.Candle,       FurnitureMaterial.Crystal) },
			{ ItemID.CrystalChair,                   (FurnitureType.Chair,        FurnitureMaterial.Crystal) },
			{ ItemID.CrystalChandelier,              (FurnitureType.Chandelier,   FurnitureMaterial.Crystal) },
			{ ItemID.CrystalChest,                   (FurnitureType.Chest,        FurnitureMaterial.Crystal) },
			{ ItemID.Fake_CrystalChest,              (FurnitureType.ChestTrapped, FurnitureMaterial.Crystal) },
			{ ItemID.CrystalClock,                   (FurnitureType.Clock,        FurnitureMaterial.Crystal) },
			{ ItemID.CrystalDoor,                    (FurnitureType.Door,         FurnitureMaterial.Crystal) },
			{ ItemID.CrystalDresser,                 (FurnitureType.Dresser,      FurnitureMaterial.Crystal) },
			{ ItemID.CrystalLamp,                    (FurnitureType.Lamp,         FurnitureMaterial.Crystal) },
			{ ItemID.CrystalLantern,                 (FurnitureType.Lantern,      FurnitureMaterial.Crystal) },
			{ ItemID.CrystalPiano,                   (FurnitureType.Piano,        FurnitureMaterial.Crystal) },
			{ ItemID.CrystalPlatform,                (FurnitureType.Platform,     FurnitureMaterial.Crystal) },
			{ ItemID.CrystalSink,                    (FurnitureType.Sink,         FurnitureMaterial.Crystal) },
			{ ItemID.CrystalSofaHowDoesThatEvenWork, (FurnitureType.Sofa,         FurnitureMaterial.Crystal) },
			{ ItemID.CrystalTable,                   (FurnitureType.Table,        FurnitureMaterial.Crystal) },
			{ ItemID.ToiletCrystal,                  (FurnitureType.Toilet,       FurnitureMaterial.Crystal) },
			{ ItemID.CrystalBlockWall,               (FurnitureType.Wall,         FurnitureMaterial.Crystal) },
			{ ItemID.CrystalWorkbench,               (FurnitureType.WorkBench,    FurnitureMaterial.Crystal) },
		};
	}
}
