using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;
using V2.Core;
using V2.PlayerHandling;
using V2.PlayerHandling.PredPlayerGoals.Amateur;
using V2.PlayerHandling.PredPlayerGoals.Skilled;

namespace V2.Items.ItemGroupUtils
{
	public partial class Furniture
	{
		public static Dictionary<int, (FurnitureType Type, FurnitureMaterial Material)> FurnitureDefinitionMappings => new Dictionary<int, (FurnitureType, FurnitureMaterial)>
		{
			{ ItemID.Bed,				(FurnitureType.Bed,				FurnitureMaterial.OakWood) },
			{ ItemID.Bookcase,			(FurnitureType.Bookcase,		FurnitureMaterial.OakWood) },
			{ ItemID.WoodenChair,		(FurnitureType.Chair,			FurnitureMaterial.OakWood) },
			{ ItemID.Chest,				(FurnitureType.Chest,			FurnitureMaterial.OakWood) },
			{ ItemID.Fake_Chest,		(FurnitureType.ChestTrapped,	FurnitureMaterial.OakWood) },
			{ ItemID.GrandfatherClock,	(FurnitureType.Clock,			FurnitureMaterial.OakWood) },
			{ ItemID.WoodenDoor,		(FurnitureType.Door,			FurnitureMaterial.OakWood) },
			{ ItemID.TallGate,			(FurnitureType.DoorTall,		FurnitureMaterial.OakWood) },
			{ ItemID.Dresser,			(FurnitureType.Dresser,			FurnitureMaterial.OakWood) },
			{ ItemID.WoodenFence,		(FurnitureType.Fence,			FurnitureMaterial.OakWood) },
			{ ItemID.Piano,				(FurnitureType.Piano,			FurnitureMaterial.OakWood) },
			{ ItemID.WoodPlatform,		(FurnitureType.Platform,		FurnitureMaterial.OakWood) },
			{ ItemID.WoodenSink,		(FurnitureType.Sink,			FurnitureMaterial.OakWood) },
			{ ItemID.Sofa,				(FurnitureType.Sofa,			FurnitureMaterial.OakWood) },
			{ ItemID.WoodenTable,		(FurnitureType.Table,			FurnitureMaterial.OakWood) },
			{ ItemID.WoodWall,			(FurnitureType.Wall,			FurnitureMaterial.OakWood) },
			{ ItemID.WorkBench,			(FurnitureType.WorkBench,		FurnitureMaterial.OakWood) },
			
			// Boreal Wood furniture
			{ ItemID.BorealWoodBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodBed,			(FurnitureType.Bed,				FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodCandle,		(FurnitureType.Candle,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodChair,		(FurnitureType.Chair,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodChest,		(FurnitureType.Chest,			FurnitureMaterial.BorealWood) },
			{ ItemID.Fake_BorealWoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodClock,		(FurnitureType.Clock,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodDoor,		(FurnitureType.Door,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodDresser,		(FurnitureType.Dresser,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodFence,		(FurnitureType.Fence,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodLamp,		(FurnitureType.Lamp,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodLantern,		(FurnitureType.Lantern,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodPiano,		(FurnitureType.Piano,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodPlatform,	(FurnitureType.Platform,		FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodSink,		(FurnitureType.Sink,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodSofa,		(FurnitureType.Sofa,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodTable,		(FurnitureType.Table,			FurnitureMaterial.BorealWood) },
			{ ItemID.ToiletBoreal,			(FurnitureType.Toilet,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodWall,		(FurnitureType.Wall,			FurnitureMaterial.BorealWood) },
			{ ItemID.BorealWoodWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.BorealWood) },
            { ItemID.BorealWoodChandelier,  (FurnitureType.Chandelier,      FurnitureMaterial.BorealWood) },
			
			// Ebonwood furniture
			{ ItemID.EbonwoodBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodBed,			(FurnitureType.Bed,				FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodCandle,		(FurnitureType.Candle,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodChair,			(FurnitureType.Chair,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodChest,			(FurnitureType.Chest,			FurnitureMaterial.Ebonwood) },
			{ ItemID.Fake_EbonwoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodClock,			(FurnitureType.Clock,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodDoor,			(FurnitureType.Door,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodFence,			(FurnitureType.Fence,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodLamp,			(FurnitureType.Lamp,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodPiano,			(FurnitureType.Piano,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodSink,			(FurnitureType.Sink,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodTable,			(FurnitureType.Table,			FurnitureMaterial.Ebonwood) },
			{ ItemID.ToiletEbonyWood,		(FurnitureType.Toilet,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodWall,			(FurnitureType.Wall,			FurnitureMaterial.Ebonwood) },
			{ ItemID.EbonwoodWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.Ebonwood) },
            { ItemID.EbonwoodChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Ebonwood) },
			
			// Shadewood furniture
			{ ItemID.ShadewoodBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodBed,			(FurnitureType.Bed,				FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodCandle,		(FurnitureType.Candle,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodChair,		(FurnitureType.Chair,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodChest,		(FurnitureType.Chest,			FurnitureMaterial.Shadewood) },
			{ ItemID.Fake_ShadewoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodClock,		(FurnitureType.Clock,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodDoor,			(FurnitureType.Door,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodFence,		(FurnitureType.Fence,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodLamp,			(FurnitureType.Lamp,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodPiano,		(FurnitureType.Piano,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodSink,			(FurnitureType.Sink,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodTable,		(FurnitureType.Table,			FurnitureMaterial.Shadewood) },
			{ ItemID.ToiletShadewood,		(FurnitureType.Toilet,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodWall,			(FurnitureType.Wall,			FurnitureMaterial.Shadewood) },
			{ ItemID.ShadewoodWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Shadewood) },
            { ItemID.ShadewoodChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Shadewood) },
			
			// Palm Wood furniture
			{ ItemID.PalmWoodBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodBed,			(FurnitureType.Bed,				FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodCandle,		(FurnitureType.Candle,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodChair,			(FurnitureType.Chair,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodChest,			(FurnitureType.Chest,			FurnitureMaterial.PalmWood) },
			{ ItemID.Fake_PalmWoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodClock,			(FurnitureType.Clock,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodDoor,			(FurnitureType.Door,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodDresser,		(FurnitureType.Dresser,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodFence,			(FurnitureType.Fence,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodLamp,			(FurnitureType.Lamp,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodLantern,		(FurnitureType.Lantern,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodPiano,			(FurnitureType.Piano,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodPlatform,		(FurnitureType.Platform,		FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodSink,			(FurnitureType.Sink,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodSofa,			(FurnitureType.Sofa,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodTable,			(FurnitureType.Table,			FurnitureMaterial.PalmWood) },
			{ ItemID.ToiletPalm,			(FurnitureType.Toilet,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodWall,			(FurnitureType.Wall,			FurnitureMaterial.PalmWood) },
			{ ItemID.PalmWoodWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.PalmWood) },
            { ItemID.PalmWoodChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.PalmWood) },
			
			// Rich Mahogany furniture
			{ ItemID.RichMahoganyBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyBed,			(FurnitureType.Bed,				FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyCandle,		(FurnitureType.Candle,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyChair,			(FurnitureType.Chair,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyChest,			(FurnitureType.Chest,			FurnitureMaterial.JungleWood) },
			{ ItemID.Fake_RichMahoganyChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyClock,			(FurnitureType.Clock,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyDoor,			(FurnitureType.Door,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyDresser,		(FurnitureType.Dresser,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyFence,			(FurnitureType.Fence,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyLamp,			(FurnitureType.Lamp,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyLantern,		(FurnitureType.Lantern,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyPiano,			(FurnitureType.Piano,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyPlatform,		(FurnitureType.Platform,		FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganySink,			(FurnitureType.Sink,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganySofa,			(FurnitureType.Sofa,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyTable,			(FurnitureType.Table,			FurnitureMaterial.JungleWood) },
			{ ItemID.ToiletRichMahogany,		(FurnitureType.Toilet,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyWall,			(FurnitureType.Wall,			FurnitureMaterial.JungleWood) },
			{ ItemID.RichMahoganyWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.JungleWood) },
            { ItemID.RichMahoganyChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.JungleWood) },
			
			// Pearlwood furniture
			{ ItemID.PearlwoodBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodBed,			(FurnitureType.Bed,				FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodCandle,		(FurnitureType.Candle,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodChair,		(FurnitureType.Chair,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodChest,		(FurnitureType.Chest,			FurnitureMaterial.Pearlwood) },
			{ ItemID.Fake_PearlwoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodClock,		(FurnitureType.Clock,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodDoor,			(FurnitureType.Door,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodFence,		(FurnitureType.Fence,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodLamp,			(FurnitureType.Lamp,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodPiano,		(FurnitureType.Piano,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodSink,			(FurnitureType.Sink,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodTable,		(FurnitureType.Table,			FurnitureMaterial.Pearlwood) },
			{ ItemID.ToiletPearlwood,		(FurnitureType.Toilet,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodWall,			(FurnitureType.Wall,			FurnitureMaterial.Pearlwood) },
			{ ItemID.PearlwoodWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Pearlwood) },
            { ItemID.PearlwoodChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Pearlwood) },
			
			// Ash Wood furniture
			{ ItemID.AshWoodBathtub,	(FurnitureType.Bathtub,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodBed,		(FurnitureType.Bed,				FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodCandle,		(FurnitureType.Candle,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodChair,		(FurnitureType.Chair,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodChest,		(FurnitureType.Chest,			FurnitureMaterial.AshWood) },
			{ ItemID.Fake_AshWoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodClock,		(FurnitureType.Clock,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodDoor,		(FurnitureType.Door,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodDresser,	(FurnitureType.Dresser,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodFence,		(FurnitureType.Fence,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodLamp,		(FurnitureType.Lamp,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodLantern,	(FurnitureType.Lantern,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodPiano,		(FurnitureType.Piano,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodPlatform,	(FurnitureType.Platform,		FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodSink,		(FurnitureType.Sink,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodSofa,		(FurnitureType.Sofa,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodTable,		(FurnitureType.Table,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodToilet,		(FurnitureType.Toilet,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodWall,		(FurnitureType.Wall,			FurnitureMaterial.AshWood) },
			{ ItemID.AshWoodWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.AshWood) },
            { ItemID.AshWoodChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.AshWood) },
			
			// Spooky Wood furniture
			{ ItemID.SpookyBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyBed,			(FurnitureType.Bed,				FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyCandle,		(FurnitureType.Candle,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyChair,		(FurnitureType.Chair,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyChest,		(FurnitureType.Chest,			FurnitureMaterial.SpookyWood) },
			{ ItemID.Fake_SpookyChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyClock,		(FurnitureType.Clock,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyDoor,		(FurnitureType.Door,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyDresser,		(FurnitureType.Dresser,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyLamp,		(FurnitureType.Lamp,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyLantern,		(FurnitureType.Lantern,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyPiano,		(FurnitureType.Piano,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyPlatform,	(FurnitureType.Platform,		FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookySink,		(FurnitureType.Sink,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookySofa,		(FurnitureType.Sofa,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyTable,		(FurnitureType.Table,			FurnitureMaterial.SpookyWood) },
			{ ItemID.ToiletSpooky,		(FurnitureType.Toilet,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyWoodWall,	(FurnitureType.Wall,			FurnitureMaterial.SpookyWood) },
			{ ItemID.SpookyWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.SpookyWood) },
            { ItemID.SpookyChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.SpookyWood) },

			// Dynasty Wood furniture
			{ ItemID.DynastyBed,		(FurnitureType.Bed,				FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyChair,		(FurnitureType.Chair,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyChest,		(FurnitureType.Chest,			FurnitureMaterial.DynastyWood) },
            { ItemID.Fake_DynastyChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyClock,		(FurnitureType.Clock,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyDoor,		(FurnitureType.Door,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyDresser,	(FurnitureType.Dresser,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyPiano,		(FurnitureType.Piano,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyPlatform,	(FurnitureType.Platform,		FurnitureMaterial.DynastyWood) },
            { ItemID.DynastySink,		(FurnitureType.Sink,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastySofa,		(FurnitureType.Sofa,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyTable,		(FurnitureType.Table,			FurnitureMaterial.DynastyWood) },
            { ItemID.WhiteDynastyWall,	(FurnitureType.Wall,			FurnitureMaterial.DynastyWood) },
            { ItemID.BlueDynastyWall,	(FurnitureType.Wall,			FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.DynastyWood) },
            { ItemID.DynastyChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.DynastyWood) },

			// Living Wood furniture
			{ ItemID.LivingWoodBed,			(FurnitureType.Bed,				FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodChair,		(FurnitureType.Chair,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodChest,		(FurnitureType.Chest,			FurnitureMaterial.LivingWood) },
            { ItemID.Fake_LivingWoodChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodClock,		(FurnitureType.Clock,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodDoor,		(FurnitureType.Door,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodDresser,		(FurnitureType.Dresser,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodPiano,		(FurnitureType.Piano,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodPlatform,	(FurnitureType.Platform,		FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodSink,		(FurnitureType.Sink,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodSofa,		(FurnitureType.Sofa,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodTable,		(FurnitureType.Table,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodWall,		(FurnitureType.Wall,			FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.LivingWood) },
            { ItemID.LivingWoodChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.LivingWood) },
			
			// Bamboo furniture
			{ ItemID.BambooBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooBed,			(FurnitureType.Bed,				FurnitureMaterial.Bamboo) },
			{ ItemID.BambooBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Bamboo) },
			{ ItemID.BambooCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Bamboo) },
			{ ItemID.BambooCandle,		(FurnitureType.Candle,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooChair,		(FurnitureType.Chair,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooChest,		(FurnitureType.Chest,			FurnitureMaterial.Bamboo) },
			{ ItemID.Fake_BambooChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Bamboo) },
			{ ItemID.BambooClock,		(FurnitureType.Clock,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooDoor,		(FurnitureType.Door,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooFence,		(FurnitureType.Fence,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooPiano,		(FurnitureType.Piano,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Bamboo) },
			{ ItemID.BambooSink,		(FurnitureType.Sink,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooTable,		(FurnitureType.Table,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooToilet,		(FurnitureType.Toilet,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooBlockWall,	(FurnitureType.Wall,			FurnitureMaterial.Bamboo) },
			{ ItemID.BambooWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Bamboo) },
            { ItemID.BambooChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Bamboo) },
			
			// Cactus furniture
			{ ItemID.CactusBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusBed,			(FurnitureType.Bed,				FurnitureMaterial.Cactus) },
			{ ItemID.CactusBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Cactus) },
			{ ItemID.CactusCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Cactus) },
			{ ItemID.CactusCandle,		(FurnitureType.Candle,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusChair,		(FurnitureType.Chair,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusChest,		(FurnitureType.Chest,			FurnitureMaterial.Cactus) },
			{ ItemID.Fake_CactusChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Cactus) },
			{ ItemID.CactusClock,		(FurnitureType.Clock,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusDoor,		(FurnitureType.Door,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusPiano,		(FurnitureType.Piano,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Cactus) },
			{ ItemID.CactusSink,		(FurnitureType.Sink,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusTable,		(FurnitureType.Table,			FurnitureMaterial.Cactus) },
			{ ItemID.ToiletCactus,		(FurnitureType.Toilet,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusWall,		(FurnitureType.Wall,			FurnitureMaterial.Cactus) },
			{ ItemID.CactusWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Cactus) },
            { ItemID.CactusChandelier,  (FurnitureType.Chandelier,      FurnitureMaterial.Cactus) },
			
			// Pumpkin furniture
			{ ItemID.PumpkinBathtub,	(FurnitureType.Bathtub,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinBed,		(FurnitureType.Bed,				FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinCandle,		(FurnitureType.Candle,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinChair,		(FurnitureType.Chair,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinChest,		(FurnitureType.Chest,			FurnitureMaterial.Pumpkin) },
			{ ItemID.Fake_PumpkinChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinClock,		(FurnitureType.Clock,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinDoor,		(FurnitureType.Door,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinDresser,	(FurnitureType.Dresser,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinLantern,	(FurnitureType.Lantern,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinPiano,		(FurnitureType.Piano,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinSink,		(FurnitureType.Sink,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinTable,		(FurnitureType.Table,			FurnitureMaterial.Pumpkin) },
			{ ItemID.ToiletPumpkin,		(FurnitureType.Toilet,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinWall,		(FurnitureType.Wall,			FurnitureMaterial.Pumpkin) },
			{ ItemID.PumpkinWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Pumpkin) },
            { ItemID.PumpkinChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Pumpkin) },
			
			// Mushroom furniture
			{ ItemID.MushroomBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomBed,			(FurnitureType.Bed,				FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomCandle,		(FurnitureType.Candle,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomChair,			(FurnitureType.Chair,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomChest,			(FurnitureType.Chest,			FurnitureMaterial.Mushroom) },
			{ ItemID.Fake_MushroomChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomClock,			(FurnitureType.Clock,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomDoor,			(FurnitureType.Door,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomLamp,			(FurnitureType.Lamp,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomPiano,			(FurnitureType.Piano,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomSink,			(FurnitureType.Sink,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomTable,			(FurnitureType.Table,			FurnitureMaterial.Mushroom) },
			{ ItemID.ToiletMushroom,		(FurnitureType.Toilet,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomWall,			(FurnitureType.Wall,			FurnitureMaterial.Mushroom) },
			{ ItemID.MushroomWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.Mushroom) },
            { ItemID.MushroomChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Mushroom) },
			
			// Marble furniture
			{ ItemID.MarbleBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleBed,			(FurnitureType.Bed,				FurnitureMaterial.Marble) },
			{ ItemID.MarbleBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Marble) },
			{ ItemID.MarbleCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Marble) },
			{ ItemID.MarbleCandle,		(FurnitureType.Candle,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleChair,		(FurnitureType.Chair,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleChest,		(FurnitureType.Chest,			FurnitureMaterial.Marble) },
			{ ItemID.Fake_MarbleChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Marble) },
			{ ItemID.MarbleClock,		(FurnitureType.Clock,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleDoor,		(FurnitureType.Door,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Marble) },
			{ ItemID.MarblePiano,		(FurnitureType.Piano,			FurnitureMaterial.Marble) },
			{ ItemID.MarblePlatform,	(FurnitureType.Platform,		FurnitureMaterial.Marble) },
			{ ItemID.MarbleSink,		(FurnitureType.Sink,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleTable,		(FurnitureType.Table,			FurnitureMaterial.Marble) },
			{ ItemID.ToiletMarble,		(FurnitureType.Toilet,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleWall,		(FurnitureType.Wall,			FurnitureMaterial.Marble) },
			{ ItemID.MarbleWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Marble) },
            { ItemID.MarbleChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Marble) },
			
			// Granite furniture
			{ ItemID.GraniteBathtub,	(FurnitureType.Bathtub,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteBed,		(FurnitureType.Bed,				FurnitureMaterial.Granite) },
			{ ItemID.GraniteBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Granite) },
			{ ItemID.GraniteCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Granite) },
			{ ItemID.GraniteCandle,		(FurnitureType.Candle,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteChair,		(FurnitureType.Chair,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteChest,		(FurnitureType.Chest,			FurnitureMaterial.Granite) },
			{ ItemID.Fake_GraniteChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Granite) },
			{ ItemID.GraniteClock,		(FurnitureType.Clock,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteDoor,		(FurnitureType.Door,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteDresser,	(FurnitureType.Dresser,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteLantern,	(FurnitureType.Lantern,			FurnitureMaterial.Granite) },
			{ ItemID.GranitePiano,		(FurnitureType.Piano,			FurnitureMaterial.Granite) },
			{ ItemID.GranitePlatform,	(FurnitureType.Platform,		FurnitureMaterial.Granite) },
			{ ItemID.GraniteSink,		(FurnitureType.Sink,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteTable,		(FurnitureType.Table,			FurnitureMaterial.Granite) },
			{ ItemID.ToiletGranite,		(FurnitureType.Toilet,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteWall,		(FurnitureType.Wall,			FurnitureMaterial.Granite) },
			{ ItemID.GraniteWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Granite) },
            { ItemID.GraniteChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Granite) },
			
			// Sandstone furniture
			{ ItemID.SandstoneBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneBed,			(FurnitureType.Bed,				FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneCandle,		(FurnitureType.Candle,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneChair,		(FurnitureType.Chair,			FurnitureMaterial.Sandstone) },
			{ ItemID.DesertChest,			(FurnitureType.Chest,			FurnitureMaterial.Sandstone) },
			{ ItemID.Fake_DesertChest,		(FurnitureType.ChestTrapped,	FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneClock,		(FurnitureType.Clock,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneDoor,			(FurnitureType.Door,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneLamp,			(FurnitureType.Lamp,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstonePiano,		(FurnitureType.Piano,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstonePlatform,		(FurnitureType.Platform,		FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneSink,			(FurnitureType.Sink,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneTable,		(FurnitureType.Table,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneToilet,		(FurnitureType.Toilet,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneWall,			(FurnitureType.Wall,			FurnitureMaterial.Sandstone) },
			{ ItemID.SandstoneWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Sandstone) },
            { ItemID.SandstoneChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Sandstone) },
			
			// Frozen furniture
			{ ItemID.FrozenBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenBed,			(FurnitureType.Bed,				FurnitureMaterial.Ice) },
			{ ItemID.FrozenBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Ice) },
			{ ItemID.FrozenCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Ice) },
			{ ItemID.FrozenCandle,		(FurnitureType.Candle,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenChair,		(FurnitureType.Chair,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenChest,		(FurnitureType.Chest,			FurnitureMaterial.Ice) },
			{ ItemID.Fake_FrozenChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Ice) },
			{ ItemID.FrozenClock,		(FurnitureType.Clock,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenDoor,		(FurnitureType.Door,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenPiano,		(FurnitureType.Piano,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Ice) },
			{ ItemID.FrozenSink,		(FurnitureType.Sink,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenTable,		(FurnitureType.Table,			FurnitureMaterial.Ice) },
			{ ItemID.ToiletFrozen,		(FurnitureType.Toilet,			FurnitureMaterial.Ice) },
			{ ItemID.FrozenWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Ice) },
            { ItemID.FrozenChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Ice) },
			
			// Reef furniture
			{ ItemID.CoralBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Coral) },
			{ ItemID.CoralBed,			(FurnitureType.Bed,				FurnitureMaterial.Coral) },
			{ ItemID.CoralBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Coral) },
			{ ItemID.CoralCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Coral) },
			{ ItemID.CoralCandle,		(FurnitureType.Candle,			FurnitureMaterial.Coral) },
			{ ItemID.CoralChair,		(FurnitureType.Chair,			FurnitureMaterial.Coral) },
			{ ItemID.CoralChest,		(FurnitureType.Chest,			FurnitureMaterial.Coral) },
			{ ItemID.Fake_CoralChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Coral) },
			{ ItemID.CoralClock,		(FurnitureType.Clock,			FurnitureMaterial.Coral) },
			{ ItemID.CoralDoor,			(FurnitureType.Door,			FurnitureMaterial.Coral) },
			{ ItemID.CoralDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Coral) },
			{ ItemID.CoralLamp,			(FurnitureType.Lamp,			FurnitureMaterial.Coral) },
			{ ItemID.CoralLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Coral) },
			{ ItemID.CoralPiano,		(FurnitureType.Piano,			FurnitureMaterial.Coral) },
			{ ItemID.CoralPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Coral) },
			{ ItemID.CoralSink,			(FurnitureType.Sink,			FurnitureMaterial.Coral) },
			{ ItemID.CoralSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Coral) },
			{ ItemID.CoralTable,		(FurnitureType.Table,			FurnitureMaterial.Coral) },
			{ ItemID.CoralToilet,		(FurnitureType.Toilet,			FurnitureMaterial.Coral) },
			{ ItemID.ReefWall,			(FurnitureType.Wall,			FurnitureMaterial.Coral) },
			{ ItemID.CoralWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Coral) },
            { ItemID.CoralChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Coral) },

			// Skyware furniture
			{ ItemID.SkywareBed,		(FurnitureType.Bed,				FurnitureMaterial.Skyware) },
            { ItemID.SkywareBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Skyware) },
            { ItemID.SkywareChair,		(FurnitureType.Chair,			FurnitureMaterial.Skyware) },
            { ItemID.SkywareChest,		(FurnitureType.Chest,			FurnitureMaterial.Skyware) },
            { ItemID.Fake_SkywareChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Skyware) },
            { ItemID.SkywareClock,		(FurnitureType.Clock,			FurnitureMaterial.Skyware) },
            { ItemID.SkywareDoor,		(FurnitureType.Door,			FurnitureMaterial.Skyware) },
            { ItemID.SkywareDresser,	(FurnitureType.Dresser,			FurnitureMaterial.Skyware) },
            { ItemID.SkywarePiano,		(FurnitureType.Piano,			FurnitureMaterial.Skyware) },
            { ItemID.SkywarePlatform,	(FurnitureType.Platform,		FurnitureMaterial.Skyware) },
            { ItemID.SkywareSink,		(FurnitureType.Sink,			FurnitureMaterial.Skyware) },
            { ItemID.SkywareSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Skyware) },
            { ItemID.SkywareTable,		(FurnitureType.Table,			FurnitureMaterial.Skyware) },
            { ItemID.DiscWall,			(FurnitureType.Wall,			FurnitureMaterial.Skyware) },
            { ItemID.SkywareWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Skyware) },
            { ItemID.SkywareChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Skyware) },

			// Meteorite furniture
			{ ItemID.MeteoriteBed,			(FurnitureType.Bed,				FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteChair,		(FurnitureType.Chair,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteChest,		(FurnitureType.Chest,			FurnitureMaterial.Meteorite) },
            { ItemID.Fake_MeteoriteChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteClock,		(FurnitureType.Clock,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteDoor,			(FurnitureType.Door,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoritePiano,		(FurnitureType.Piano,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoritePlatform,		(FurnitureType.Platform,		FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteSink,			(FurnitureType.Sink,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteTable,		(FurnitureType.Table,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteBrickWall,	(FurnitureType.Wall,			FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Meteorite) },
            { ItemID.MeteoriteChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Meteorite) },

			// Blue Dungeon furniture
			{ ItemID.BlueDungeonBed,		(FurnitureType.Bed,				FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonChair,		(FurnitureType.Chair,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonChest,		(FurnitureType.Chest,			FurnitureMaterial.Dungeon) },
            { ItemID.Fake_BlueDungeonChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Dungeon) },
            { ItemID.DungeonClockBlue,		(FurnitureType.Clock,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonDoor,		(FurnitureType.Door,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonDresser,	(FurnitureType.Dresser,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonPiano,		(FurnitureType.Piano,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueBrickPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonSink,		(FurnitureType.Sink,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonTable,		(FurnitureType.Table,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueBrickWall,			(FurnitureType.Wall,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueBrickWallUnsafe,	(FurnitureType.Wall,			FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Dungeon) },
            { ItemID.BlueDungeonChandelier,	(FurnitureType.Chandelier,		FurnitureMaterial.Dungeon) },

			// Pink Dungeon furniture
			{ ItemID.PinkDungeonBed,		(FurnitureType.Bed,				FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonChair,		(FurnitureType.Chair,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonChest,		(FurnitureType.Chest,			FurnitureMaterial.Dungeon) },
            { ItemID.Fake_PinkDungeonChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Dungeon) },
            { ItemID.DungeonClockPink,		(FurnitureType.Clock,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonDoor,		(FurnitureType.Door,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonDresser,	(FurnitureType.Dresser,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonPiano,		(FurnitureType.Piano,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkBrickPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonSink,		(FurnitureType.Sink,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonTable,		(FurnitureType.Table,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkBrickWall,			(FurnitureType.Wall,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkBrickWallUnsafe,	(FurnitureType.Wall,			FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Dungeon) },
            { ItemID.PinkDungeonChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Dungeon) },

			// Green Dungeon furniture
			{ ItemID.GreenDungeonBed,			(FurnitureType.Bed,				FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonChair,			(FurnitureType.Chair,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonChest,			(FurnitureType.Chest,			FurnitureMaterial.Dungeon) },
            { ItemID.Fake_GreenDungeonChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Dungeon) },
            { ItemID.DungeonClockGreen,			(FurnitureType.Clock,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonDoor,			(FurnitureType.Door,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonPiano,			(FurnitureType.Piano,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenBrickPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonSink,			(FurnitureType.Sink,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonTable,			(FurnitureType.Table,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenBrickWall,			(FurnitureType.Wall,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenBrickWallUnsafe,		(FurnitureType.Wall,			FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.Dungeon) },
            { ItemID.GreenDungeonChandelier,    (FurnitureType.Chandelier,      FurnitureMaterial.Dungeon) },

			// Lesion furniture
			{ ItemID.LesionBed,			(FurnitureType.Bed,				FurnitureMaterial.Lesion) },
            { ItemID.LesionBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Lesion) },
            { ItemID.LesionChair,		(FurnitureType.Chair,			FurnitureMaterial.Lesion) },
            { ItemID.LesionChest,		(FurnitureType.Chest,			FurnitureMaterial.Lesion) },
            { ItemID.Fake_LesionChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Lesion) },
            { ItemID.LesionClock,		(FurnitureType.Clock,			FurnitureMaterial.Lesion) },
            { ItemID.LesionDoor,		(FurnitureType.Door,			FurnitureMaterial.Lesion) },
            { ItemID.LesionDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Lesion) },
            { ItemID.LesionPiano,		(FurnitureType.Piano,			FurnitureMaterial.Lesion) },
            { ItemID.LesionPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Lesion) },
            { ItemID.LesionSink,		(FurnitureType.Sink,			FurnitureMaterial.Lesion) },
            { ItemID.LesionSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Lesion) },
            { ItemID.LesionTable,		(FurnitureType.Table,			FurnitureMaterial.Lesion) },
            { ItemID.LesionBlockWall,	(FurnitureType.Wall,			FurnitureMaterial.Lesion) },
            { ItemID.LesionWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Lesion) },
            { ItemID.LesionChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Lesion) },

			// Flesh furniture
			{ ItemID.FleshBed,			(FurnitureType.Bed,				FurnitureMaterial.Flesh) },
            { ItemID.FleshBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Flesh) },
            { ItemID.FleshChair,		(FurnitureType.Chair,			FurnitureMaterial.Flesh) },
            { ItemID.FleshChest,		(FurnitureType.Chest,			FurnitureMaterial.Flesh) },
            { ItemID.Fake_FleshChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Flesh) },
            { ItemID.FleshClock,		(FurnitureType.Clock,			FurnitureMaterial.Flesh) },
            { ItemID.FleshDoor,			(FurnitureType.Door,			FurnitureMaterial.Flesh) },
            { ItemID.FleshDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Flesh) },
            { ItemID.FleshPiano,		(FurnitureType.Piano,			FurnitureMaterial.Flesh) },
            { ItemID.FleshPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Flesh) },
            { ItemID.FleshSink,			(FurnitureType.Sink,			FurnitureMaterial.Flesh) },
            { ItemID.FleshSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Flesh) },
            { ItemID.FleshTable,		(FurnitureType.Table,			FurnitureMaterial.Flesh) },
            { ItemID.FleshBlockWall,	(FurnitureType.Wall,			FurnitureMaterial.Flesh) },
            { ItemID.FleshWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Flesh) },
            { ItemID.FleshChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Flesh) },

			// Bone furniture
			{ ItemID.BoneBed,			(FurnitureType.Bed,				FurnitureMaterial.Bone) },
            { ItemID.BoneBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Bone) },
            { ItemID.BoneChair,			(FurnitureType.Chair,			FurnitureMaterial.Bone) },
            { ItemID.BoneChest,			(FurnitureType.Chest,			FurnitureMaterial.Bone) },
            { ItemID.Fake_BoneChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Bone) },
            { ItemID.BoneClock,			(FurnitureType.Clock,			FurnitureMaterial.Bone) },
            { ItemID.BoneDoor,			(FurnitureType.Door,			FurnitureMaterial.Bone) },
            { ItemID.BoneDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Bone) },
            { ItemID.BonePiano,			(FurnitureType.Piano,			FurnitureMaterial.Bone) },
            { ItemID.BonePlatform,		(FurnitureType.Platform,		FurnitureMaterial.Bone) },
            { ItemID.BoneSink,			(FurnitureType.Sink,			FurnitureMaterial.Bone) },
            { ItemID.BoneSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Bone) },
            { ItemID.BoneTable,			(FurnitureType.Table,			FurnitureMaterial.Bone) },
            { ItemID.BoneBlockWall,		(FurnitureType.Wall,			FurnitureMaterial.Bone) },
            { ItemID.BoneWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.Bone) },
            { ItemID.BoneChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Bone) },

			// Golden furniture (delicious shiny furniture....... :9)
			{ ItemID.GoldenBathtub,		(FurnitureType.Bathtub,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenBed,			(FurnitureType.Bed,				FurnitureMaterial.Golden) },
			{ ItemID.GoldenBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Golden) },
			{ ItemID.GoldenCandelabra,	(FurnitureType.Candelabra,		FurnitureMaterial.Golden) },
			{ ItemID.GoldenCandle,		(FurnitureType.Candle,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenChair,		(FurnitureType.Chair,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenChandelier,	(FurnitureType.Chandelier,		FurnitureMaterial.Golden) },
			{ ItemID.GoldenChest,		(FurnitureType.Chest,			FurnitureMaterial.Golden) },
			{ ItemID.Fake_GoldenChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Golden) },
			{ ItemID.GoldenClock,		(FurnitureType.Clock,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenDoor,		(FurnitureType.Door,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenLamp,		(FurnitureType.Lamp,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenLantern,		(FurnitureType.Lantern,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenPiano,		(FurnitureType.Piano,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Golden) },
			{ ItemID.GoldenSink,		(FurnitureType.Sink,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenTable,		(FurnitureType.Table,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenToilet,		(FurnitureType.Toilet,			FurnitureMaterial.Golden) },
			{ ItemID.GoldenWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Golden) },

			// Crystal furniture (how does that even work?)
			{ ItemID.CrystalBathtub,					(FurnitureType.Bathtub,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalBed,						(FurnitureType.Bed,				FurnitureMaterial.Crystal) },
			{ ItemID.CrystalBookCase,					(FurnitureType.Bookcase,		FurnitureMaterial.Crystal) },
			{ ItemID.CrystalCandelabra,					(FurnitureType.Candelabra,		FurnitureMaterial.Crystal) },
			{ ItemID.CrystalCandle,						(FurnitureType.Candle,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalChair,						(FurnitureType.Chair,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalChandelier,					(FurnitureType.Chandelier,		FurnitureMaterial.Crystal) },
			{ ItemID.CrystalChest,						(FurnitureType.Chest,			FurnitureMaterial.Crystal) },
			{ ItemID.Fake_CrystalChest,					(FurnitureType.ChestTrapped,	FurnitureMaterial.Crystal) },
			{ ItemID.CrystalClock,						(FurnitureType.Clock,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalDoor,						(FurnitureType.Door,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalDresser,					(FurnitureType.Dresser,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalLamp,						(FurnitureType.Lamp,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalLantern,					(FurnitureType.Lantern,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalPiano,						(FurnitureType.Piano,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalPlatform,					(FurnitureType.Platform,		FurnitureMaterial.Crystal) },
			{ ItemID.CrystalSink,						(FurnitureType.Sink,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalSofaHowDoesThatEvenWork,	(FurnitureType.Sofa,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalTable,						(FurnitureType.Table,			FurnitureMaterial.Crystal) },
			{ ItemID.ToiletCrystal,						(FurnitureType.Toilet,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalBlockWall,					(FurnitureType.Wall,			FurnitureMaterial.Crystal) },
			{ ItemID.CrystalWorkbench,					(FurnitureType.WorkBench,		FurnitureMaterial.Crystal) },

			// Glass furniture
			{ ItemID.GlassBed,			(FurnitureType.Bed,				FurnitureMaterial.Glass) },
            { ItemID.GlassBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Glass) },
            { ItemID.GlassChair,		(FurnitureType.Chair,			FurnitureMaterial.Glass) },
            { ItemID.GlassChest,		(FurnitureType.Chest,			FurnitureMaterial.Glass) },
            { ItemID.Fake_GlassChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Glass) },
            { ItemID.GlassClock,		(FurnitureType.Clock,			FurnitureMaterial.Glass) },
            { ItemID.GlassDoor,			(FurnitureType.Door,			FurnitureMaterial.Glass) },
            { ItemID.GlassDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Glass) },
            { ItemID.GlassPiano,		(FurnitureType.Piano,			FurnitureMaterial.Glass) },
            { ItemID.GlassPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Glass) },
            { ItemID.GlassSink,			(FurnitureType.Sink,			FurnitureMaterial.Glass) },
            { ItemID.GlassSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Glass) },
            { ItemID.GlassTable,		(FurnitureType.Table,			FurnitureMaterial.Glass) },
            { ItemID.GlassWall,			(FurnitureType.Wall,			FurnitureMaterial.Glass) },
            { ItemID.GlassWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Glass) },
            { ItemID.GlassChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Glass) },

			// Balloon furniture
			{ ItemID.BalloonBed,				(FurnitureType.Bed,				FurnitureMaterial.Balloon) },
            { ItemID.BalloonBookcase,			(FurnitureType.Bookcase,		FurnitureMaterial.Balloon) },
            { ItemID.BalloonChair,				(FurnitureType.Chair,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonChest,				(FurnitureType.Chest,			FurnitureMaterial.Balloon) },
            { ItemID.Fake_BalloonChest,			(FurnitureType.ChestTrapped,	FurnitureMaterial.Balloon) },
            { ItemID.BalloonClock,				(FurnitureType.Clock,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonDoor,				(FurnitureType.Door,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonDresser,			(FurnitureType.Dresser,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonPiano,				(FurnitureType.Piano,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonPlatform,			(FurnitureType.Platform,		FurnitureMaterial.Balloon) },
            { ItemID.BalloonSink,				(FurnitureType.Sink,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonSofa,				(FurnitureType.Sofa,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonTable,				(FurnitureType.Table,			FurnitureMaterial.Balloon) },
            { ItemID.SillyBalloonGreenWall,		(FurnitureType.Wall,			FurnitureMaterial.Balloon) },
            { ItemID.SillyBalloonPinkWall,		(FurnitureType.Wall,			FurnitureMaterial.Balloon) },
            { ItemID.SillyBalloonPurpleWall,	(FurnitureType.Wall,			FurnitureMaterial.Balloon) },
            { ItemID.BalloonWorkbench,			(FurnitureType.WorkBench,		FurnitureMaterial.Balloon) },
            { ItemID.BalloonChandelier,			(FurnitureType.Chandelier,      FurnitureMaterial.Balloon) },

			// Slime furniture
			{ ItemID.SlimeBed,			(FurnitureType.Bed,				FurnitureMaterial.Slime) },
            { ItemID.SlimeBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Slime) },
            { ItemID.SlimeChair,		(FurnitureType.Chair,			FurnitureMaterial.Slime) },
            { ItemID.SlimeChest,		(FurnitureType.Chest,			FurnitureMaterial.Slime) },
            { ItemID.Fake_SlimeChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Slime) },
            { ItemID.SlimeClock,		(FurnitureType.Clock,			FurnitureMaterial.Slime) },
            { ItemID.SlimeDoor,			(FurnitureType.Door,			FurnitureMaterial.Slime) },
            { ItemID.SlimeDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Slime) },
            { ItemID.SlimePiano,		(FurnitureType.Piano,			FurnitureMaterial.Slime) },
            { ItemID.SlimePlatform,		(FurnitureType.Platform,		FurnitureMaterial.Slime) },
            { ItemID.SlimeSink,			(FurnitureType.Sink,			FurnitureMaterial.Slime) },
            { ItemID.SlimeSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Slime) },
            { ItemID.SlimeTable,		(FurnitureType.Table,			FurnitureMaterial.Slime) },
            { ItemID.SlimeBlockWall,	(FurnitureType.Wall,			FurnitureMaterial.Slime) },
            { ItemID.SlimeWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Slime) },
            { ItemID.SlimeChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Slime) },

			// Honey furniture
			{ ItemID.HoneyBed,			(FurnitureType.Bed,				FurnitureMaterial.Honey) },
            { ItemID.HoneyBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Honey) },
            { ItemID.HoneyChair,		(FurnitureType.Chair,			FurnitureMaterial.Honey) },
            { ItemID.HoneyChest,		(FurnitureType.Chest,			FurnitureMaterial.Honey) },
            { ItemID.Fake_HoneyChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Honey) },
            { ItemID.HoneyClock,		(FurnitureType.Clock,			FurnitureMaterial.Honey) },
            { ItemID.HoneyDoor,			(FurnitureType.Door,			FurnitureMaterial.Honey) },
            { ItemID.HoneyDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Honey) },
            { ItemID.HoneyPiano,		(FurnitureType.Piano,			FurnitureMaterial.Honey) },
            { ItemID.HoneyPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Honey) },
            { ItemID.HoneySink,			(FurnitureType.Sink,			FurnitureMaterial.Honey) },
            { ItemID.HoneySofa,			(FurnitureType.Sofa,			FurnitureMaterial.Honey) },
            { ItemID.HoneyTable,		(FurnitureType.Table,			FurnitureMaterial.Honey) },
            { ItemID.HiveWall,			(FurnitureType.Wall,			FurnitureMaterial.Honey) },
            { ItemID.HoneyWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Honey) },
            { ItemID.HoneyChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Honey) },

			// Spider furniture
			{ ItemID.SpiderBed,											(FurnitureType.Bed,				FurnitureMaterial.Spider) },
            { ItemID.SpiderBookcase,									(FurnitureType.Bookcase,		FurnitureMaterial.Spider) },
            { ItemID.SpiderChair,										(FurnitureType.Chair,			FurnitureMaterial.Spider) },
            { ItemID.SpiderChest,										(FurnitureType.Chest,			FurnitureMaterial.Spider) },
            { ItemID.Fake_SpiderChest,									(FurnitureType.ChestTrapped,	FurnitureMaterial.Spider) },
            { ItemID.SpiderClock,										(FurnitureType.Clock,			FurnitureMaterial.Spider) },
            { ItemID.SpiderDoor,										(FurnitureType.Door,			FurnitureMaterial.Spider) },
            { ItemID.SpiderDresser,										(FurnitureType.Dresser,			FurnitureMaterial.Spider) },
            { ItemID.SpiderPiano,										(FurnitureType.Piano,			FurnitureMaterial.Spider) },
            { ItemID.SpiderPlatform,									(FurnitureType.Platform,		FurnitureMaterial.Spider) },
            { ItemID.SpiderSinkSpiderSinkDoesWhateverASpiderSinkDoes,	(FurnitureType.Sink,			FurnitureMaterial.Spider) }, //are you fr rn
            { ItemID.SpiderSofa,										(FurnitureType.Sofa,			FurnitureMaterial.Spider) },
            { ItemID.SpiderTable,										(FurnitureType.Table,			FurnitureMaterial.Spider) },
            { ItemID.SpiderWall,										(FurnitureType.Wall,			FurnitureMaterial.Spider) },
            { ItemID.SpiderWorkbench,									(FurnitureType.WorkBench,		FurnitureMaterial.Spider) },
            { ItemID.SpiderChandelier,									(FurnitureType.Chandelier,      FurnitureMaterial.Spider) },

			// Steampunk furniture
			{ ItemID.SteampunkBed,			(FurnitureType.Bed,				FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkChair,		(FurnitureType.Chair,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkChest,		(FurnitureType.Chest,			FurnitureMaterial.Steampunk) },
            { ItemID.Fake_SteampunkChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkClock,		(FurnitureType.Clock,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkDoor,			(FurnitureType.Door,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkPiano,		(FurnitureType.Piano,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkSink,			(FurnitureType.Sink,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkTable,		(FurnitureType.Table,			FurnitureMaterial.Steampunk) },
            { ItemID.CogWall,				(FurnitureType.Wall,			FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkWorkBench,	(FurnitureType.WorkBench,		FurnitureMaterial.Steampunk) },
            { ItemID.SteampunkChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Steampunk) },
			
			// Lihzahrd furniture (hah wrote the name right first try!)
			{ ItemID.LihzahrdBed,			(FurnitureType.Bed,				FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdChair,			(FurnitureType.Chair,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdChest,			(FurnitureType.Chest,			FurnitureMaterial.Lihzahrd) },
            { ItemID.Fake_LihzahrdChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdClock,			(FurnitureType.Clock,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdDoor,			(FurnitureType.Door,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdPiano,			(FurnitureType.Piano,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdSink,			(FurnitureType.Sink,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdTable,			(FurnitureType.Table,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdBrickWall,		(FurnitureType.Wall,			FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.Lihzahrd) },
            { ItemID.LihzahrdChandelier,    (FurnitureType.Chandelier,      FurnitureMaterial.Lihzahrd) },
			
			// Martian Furniture
			{ ItemID.MartianBed,			(FurnitureType.Bed,				FurnitureMaterial.Martian) },
            { ItemID.MartianHolobookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Martian) },
            { ItemID.MartianHoverChair,		(FurnitureType.Chair,			FurnitureMaterial.Martian) },
            { ItemID.MartianChest,			(FurnitureType.Chest,			FurnitureMaterial.Martian) },
            { ItemID.Fake_MartianChest,		(FurnitureType.ChestTrapped,	FurnitureMaterial.Martian) },
            { ItemID.MartianAstroClock,		(FurnitureType.Clock,			FurnitureMaterial.Martian) },
            { ItemID.MartianDoor,			(FurnitureType.Door,			FurnitureMaterial.Martian) },
            { ItemID.MartianDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Martian) },
            { ItemID.MartianPiano,			(FurnitureType.Piano,			FurnitureMaterial.Martian) },
            { ItemID.MartianPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Martian) },
            { ItemID.MartianSink,			(FurnitureType.Sink,			FurnitureMaterial.Martian) },
            { ItemID.MartianSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Martian) },
            { ItemID.MartianTable,			(FurnitureType.Table,			FurnitureMaterial.Martian) },
            { ItemID.MartianConduitWall,	(FurnitureType.Wall,			FurnitureMaterial.Martian) },
            { ItemID.MartianWorkBench,		(FurnitureType.WorkBench,		FurnitureMaterial.Martian) },
            { ItemID.MartianChandelier,		(FurnitureType.Chandelier,      FurnitureMaterial.Martian) },
			
			// Solar Furniture
			{ ItemID.SolarBed,			(FurnitureType.Bed,				FurnitureMaterial.Solar) },
            { ItemID.SolarBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Solar) },
            { ItemID.SolarChair,		(FurnitureType.Chair,			FurnitureMaterial.Solar) },
            { ItemID.SolarChest,		(FurnitureType.Chest,			FurnitureMaterial.Solar) },
            { ItemID.Fake_SolarChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Solar) },
            { ItemID.SolarClock,		(FurnitureType.Clock,			FurnitureMaterial.Solar) },
            { ItemID.SolarDoor,			(FurnitureType.Door,			FurnitureMaterial.Solar) },
            { ItemID.SolarDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Solar) },
            { ItemID.SolarPiano,		(FurnitureType.Piano,			FurnitureMaterial.Solar) },
            { ItemID.SolarPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Solar) },
            { ItemID.SolarSink,			(FurnitureType.Sink,			FurnitureMaterial.Solar) },
            { ItemID.SolarSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Solar) },
            { ItemID.SolarTable,		(FurnitureType.Table,			FurnitureMaterial.Solar) },
            { ItemID.SolarBrickWall,	(FurnitureType.Wall,			FurnitureMaterial.Solar) },
            { ItemID.SolarWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Solar) },
            { ItemID.SolarChandelier,   (FurnitureType.Chandelier,      FurnitureMaterial.Solar) },
			
			// Vortex Furniture
			{ ItemID.VortexBed,			(FurnitureType.Bed,				FurnitureMaterial.Vortex) },
            { ItemID.VortexBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Vortex) },
            { ItemID.VortexChair,		(FurnitureType.Chair,			FurnitureMaterial.Vortex) },
            { ItemID.VortexChest,		(FurnitureType.Chest,			FurnitureMaterial.Vortex) },
            { ItemID.Fake_VortexChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Vortex) },
            { ItemID.VortexClock,		(FurnitureType.Clock,			FurnitureMaterial.Vortex) },
            { ItemID.VortexDoor,		(FurnitureType.Door,			FurnitureMaterial.Vortex) },
            { ItemID.VortexDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Vortex) },
            { ItemID.VortexPiano,		(FurnitureType.Piano,			FurnitureMaterial.Vortex) },
            { ItemID.VortexPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Vortex) },
            { ItemID.VortexSink,		(FurnitureType.Sink,			FurnitureMaterial.Vortex) },
            { ItemID.VortexSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Vortex) },
            { ItemID.VortexTable,		(FurnitureType.Table,			FurnitureMaterial.Vortex) },
            { ItemID.VortexBrickWall,	(FurnitureType.Wall,			FurnitureMaterial.Vortex) },
            { ItemID.VortexWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Vortex) },
            { ItemID.VortexChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Vortex) },
			
			// Nebula Furniture
			{ ItemID.NebulaBed,			(FurnitureType.Bed,				FurnitureMaterial.Nebula) },
            { ItemID.NebulaBookcase,	(FurnitureType.Bookcase,		FurnitureMaterial.Nebula) },
            { ItemID.NebulaChair,		(FurnitureType.Chair,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaChest,		(FurnitureType.Chest,			FurnitureMaterial.Nebula) },
            { ItemID.Fake_NebulaChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Nebula) },
            { ItemID.NebulaClock,		(FurnitureType.Clock,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaDoor,		(FurnitureType.Door,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaPiano,		(FurnitureType.Piano,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaPlatform,	(FurnitureType.Platform,		FurnitureMaterial.Nebula) },
            { ItemID.NebulaSink,		(FurnitureType.Sink,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaSofa,		(FurnitureType.Sofa,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaTable,		(FurnitureType.Table,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaBrickWall,	(FurnitureType.Wall,			FurnitureMaterial.Nebula) },
            { ItemID.NebulaWorkbench,	(FurnitureType.WorkBench,		FurnitureMaterial.Nebula) },
            { ItemID.NebulaChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Nebula) },
			
			// Stardust Furniture
			{ ItemID.StardustBed,			(FurnitureType.Bed,				FurnitureMaterial.Stardust) },
            { ItemID.StardustBookcase,		(FurnitureType.Bookcase,		FurnitureMaterial.Stardust) },
            { ItemID.StardustChair,			(FurnitureType.Chair,			FurnitureMaterial.Stardust) },
            { ItemID.StardustChest,			(FurnitureType.Chest,			FurnitureMaterial.Stardust) },
            { ItemID.Fake_StardustChest,	(FurnitureType.ChestTrapped,	FurnitureMaterial.Stardust) },
            { ItemID.StardustClock,			(FurnitureType.Clock,			FurnitureMaterial.Stardust) },
            { ItemID.StardustDoor,			(FurnitureType.Door,			FurnitureMaterial.Stardust) },
            { ItemID.StardustDresser,		(FurnitureType.Dresser,			FurnitureMaterial.Stardust) },
            { ItemID.StardustPiano,			(FurnitureType.Piano,			FurnitureMaterial.Stardust) },
            { ItemID.StardustPlatform,		(FurnitureType.Platform,		FurnitureMaterial.Stardust) },
            { ItemID.StardustSink,			(FurnitureType.Sink,			FurnitureMaterial.Stardust) },
            { ItemID.StardustSofa,			(FurnitureType.Sofa,			FurnitureMaterial.Stardust) },
            { ItemID.StardustTable,			(FurnitureType.Table,			FurnitureMaterial.Stardust) },
            { ItemID.StardustBrickWall,		(FurnitureType.Wall,			FurnitureMaterial.Stardust) },
            { ItemID.StardustWorkbench,		(FurnitureType.WorkBench,		FurnitureMaterial.Stardust) },
            { ItemID.StardustChandelier,	(FurnitureType.Chandelier,      FurnitureMaterial.Stardust) },

			// Misc Furniture
			{ ItemID.DungeonDoor,			(FurnitureType.Door,            FurnitureMaterial.BorealWood) },
            { ItemID.StoneDoor,				(FurnitureType.Door,            FurnitureMaterial.Stone) },
            { ItemID.IronDoor,				(FurnitureType.Door,            FurnitureMaterial.Metal) },
            { ItemID.LeadDoor,				(FurnitureType.Door,            FurnitureMaterial.Metal) },
            { ItemID.BanquetTable,			(FurnitureType.Table,           FurnitureMaterial.OakWood) },
            { ItemID.Bar,					(FurnitureType.Table,           FurnitureMaterial.OakWood) },
            { ItemID.BarStool,				(FurnitureType.Chair,           FurnitureMaterial.OakWood) },
            { ItemID.PicnicTable,			(FurnitureType.Table,           FurnitureMaterial.OakWood) },
            { ItemID.PicnicTableWithCloth,	(FurnitureType.Table,           FurnitureMaterial.OakWood) },
            { ItemID.GothicTable,			(FurnitureType.Table,           FurnitureMaterial.Shadewood) },
            { ItemID.GothicBookcase,		(FurnitureType.Bookcase,        FurnitureMaterial.Shadewood) },
            { ItemID.GothicChair,			(FurnitureType.Chair,           FurnitureMaterial.Shadewood) },
            { ItemID.GothicWorkBench,		(FurnitureType.WorkBench,       FurnitureMaterial.Shadewood) },

        };
	}
}
