using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using V2.Core.StruggleSystem;

namespace V2.NPCs.Vanilla.BloodMoon
{
	public static partial class TheBrideStuff
	{
		public class TheBrideStruggleChart : StruggleChart
		{
			public override double ProgressRate => 4.0f;
			public override double NoteSpacingFactor => 1.0f;
			public override List<StruggleChartNote[]> Notes =>
			[
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Left) ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Left) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Left) ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Left) ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Left) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Left) ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Down) ],
				[ null ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Up) ],
				[ null ],
				[ null ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ new StruggleChartNote(NoteDirection.Right) ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
				[ null ],
			];
		}
	}
}
